site_name: INAV Lua Telemetry
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/luatelemetry

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tasklist
nav:
  - "INAV Lua Telemetry": index.md
  - "Getting Started": Getting-Started.md
  - "Configuration Settings": Configuration-Settings.md
  - "Screen Description": Screen-Description.md
  - "Tips & Common Problems": Tips-&-Common-Problems.md
  - "Upgrade": Upgrade.md
  - "Multilingual Support": Multilingual-Support.md
  - "Change Log": Change-Log.md